"use client";

import Link from "next/link";
import { ArrowLeft, GitBranch, Waypoints } from "lucide-react";
import { Header } from "@/components/header";
import { Badge } from "@/components/ui/badge";
import { TracebackGraph } from "@/components/incident/traceback-graph";
import { EvidenceLogs } from "@/components/incident/evidence-logs";
import { PostmortemPanel } from "@/components/incident/postmortem-panel";
import { useHaalandStore } from "@/lib/store";
import { timeAgo } from "@/lib/format";

export function IncidentDetail({ id }: { id: string }) {
  const incident = useHaalandStore((s) => s.incidents.find((i) => i.id === id));

  if (!incident) {
    return (
      <div className="flex flex-1 flex-col">
        <Header />
        <main className="mx-auto flex max-w-7xl flex-1 flex-col items-center justify-center gap-3 px-6 py-16 text-center">
          <p className="text-lg font-medium">Incident {id} not found</p>
          <p className="text-sm text-muted-foreground">
            It may not exist yet in this session&apos;s in-memory store.
          </p>
          <Link href="/" className="text-sm text-primary hover:underline">
            Back to services
          </Link>
        </main>
      </div>
    );
  }

  const severityVariant = incident.severity === "P1" ? "destructive" : "secondary";

  return (
    <div className="flex flex-1 flex-col">
      <Header />
      <main className="mx-auto flex w-full max-w-[1600px] flex-1 flex-col gap-4 px-6 py-6">
        <div className="flex flex-col gap-3">
          <Link
            href="/"
            className="flex w-fit items-center gap-1 text-xs text-muted-foreground hover:text-foreground"
          >
            <ArrowLeft className="h-3.5 w-3.5" />
            Back to services
          </Link>

          <div className="flex flex-wrap items-center gap-3">
            <span className="font-mono text-lg font-semibold tabular-nums">
              {incident.id}
            </span>
            <Badge variant={incident.status === "active" ? severityVariant : "outline"}>
              {incident.status === "active" ? `${incident.severity} Active` : "Resolved"}
            </Badge>
            <span className="text-sm text-muted-foreground">
              {incident.serviceName}
            </span>
            <span className="text-sm text-muted-foreground">
              &bull; opened {timeAgo(incident.createdAt)}
            </span>
          </div>

          <h1 className="text-xl font-semibold tracking-tight">{incident.title}</h1>
        </div>

        <div className="grid grid-cols-1 gap-4 xl:h-[calc(100vh-220px)] xl:grid-cols-[1.1fr_0.9fr_1fr]">
          <section className="flex h-[420px] min-h-0 min-w-0 flex-col gap-2 rounded-xl border border-border bg-card p-4 xl:h-full">
            <div className="flex items-center gap-2 text-sm font-semibold">
              <Waypoints className="h-4 w-4 text-muted-foreground" />
              Traceback Graph
            </div>
            <p className="text-xs text-muted-foreground">
              Dependency map with blast radius highlighted
            </p>
            <div className="min-h-0 flex-1 overflow-hidden rounded-lg border border-border/60">
              <TracebackGraph nodes={incident.graphNodes} edges={incident.graphEdges} />
            </div>
          </section>

          <section className="flex h-[420px] min-h-0 min-w-0 flex-col gap-2 rounded-xl border border-border bg-card p-4 xl:h-full">
            <div className="flex items-center gap-2 text-sm font-semibold">
              <GitBranch className="h-4 w-4 text-muted-foreground" />
              Evidence &amp; Logs
            </div>
            <p className="text-xs text-muted-foreground">
              Captured stack trace from the failing service
            </p>
            <div className="min-h-0 flex-1 overflow-hidden">
              <EvidenceLogs logs={incident.logs} />
            </div>
          </section>

          <section className="flex h-[420px] min-h-0 min-w-0 flex-col gap-2 rounded-xl border border-border bg-card p-4 xl:h-full">
            <div className="text-sm font-semibold">Post-Mortem &amp; AI Analysis</div>
            <p className="text-xs text-muted-foreground">
              Generated by the background diagnostic agent
            </p>
            <div className="min-h-0 flex-1 overflow-hidden">
              <PostmortemPanel
                rootCause={incident.rootCause}
                remediation={incident.remediation}
                auditTimeline={incident.auditTimeline}
                resolved={incident.status === "resolved"}
              />
            </div>
          </section>
        </div>
      </main>
    </div>
  );
}
