"""Deterministic, offline provider. Default (`HAALAND_LLM_PROVIDER=fake`) so
the whole loop — and CI — runs with zero network egress and zero API spend.
Per docs/02's testing table: "Never hit the API in CI. Record real responses
once, replay forever." This is that replay target's simplest case: fixed
fixtures keyed by output schema, not recorded traffic.

Also doubles as `FakeLLM` for unit tests that need to inject scripted
responses — pass `overrides={SchemaClass: lambda req: SchemaClass(...)}`.
"""

from __future__ import annotations

import time
from collections.abc import Callable

from pydantic import BaseModel

from haaland.domain.models import (
    Classification,
    Diagnosis,
    FixCandidate,
    FixEvaluation,
    PostmortemProse,
    RegressionTest,
    RemediationDraft,
)
from haaland.llm.base import LLMRequest, LLMResult, Usage


def _fake_classification(_: LLMRequest) -> Classification:
    return Classification(
        severity="P2",
        confidence=0.75,
        customer_impact="degraded",
        affected_services=["target-service"],
        blast_radius_estimate="single service, no fan-out observed",
        rationale="Fake provider: deterministic placeholder classification for offline runs.",
        requires_immediate_page=False,
    )


def _fake_diagnosis(_: LLMRequest) -> Diagnosis:
    return Diagnosis(
        root_cause="Fake provider placeholder: see culprit_locations for the top code candidate.",
        category="logic_bug",
        confidence=0.6,
        culprit_locations=[],
        supporting_evidence=[
            {"evidence_id": "fake-0", "excerpt": "n/a", "why_relevant": "fake provider output"}
        ],
        contradicting_evidence=[],
        recommended_strategy="code_fix",
        strategy_rationale="Fake provider: default to a direct code fix.",
    )


def _fake_evaluation(_: LLMRequest) -> FixEvaluation:
    return FixEvaluation(
        candidates=[
            FixCandidate(
                summary="Apply the minimal fix at the located line",
                approach="Direct patch",
                risk="low",
                rationale="Fake provider placeholder",
            )
        ],
        selected_index=0,
        selection_rationale="Only candidate under the fake provider.",
    )


def _fake_remediation(_: LLMRequest) -> RemediationDraft:
    return RemediationDraft(
        strategy="code_fix",
        pr_title="fix: placeholder fix from fake LLM provider",
        pr_body_markdown="This PR was drafted automatically and requires human review.\n\n"
        "Generated by the `fake` LLM provider (no real model call) — it does not touch "
        "real source, only adds a marker file, so it never claims to fix anything it "
        "hasn't actually reasoned about.",
        # A real remediation never has zero files (schema enforces min_length=1) and a
        # generic offline provider has no business guessing at the target repo's real
        # source — so it adds one syntactically-valid, harmless new file instead of
        # touching anything under diagnosis.culprit_locations.
        files=[
            {
                "path": "HAALAND_FAKE_FIX_MARKER.py",
                "action": "modify",
                "new_content": '"""Placeholder written by the fake LLM provider — not a real fix."""\n',
                "change_summary": "Marker file proving the patch/check/PR pipeline ran end to end.",
            }
        ],
        risk_assessment="Fake provider: no risk assessment performed.",
        rollback_instructions="git revert this commit.",
        verification_steps=["Run the generated regression test."],
    )


def _fake_test(_: LLMRequest) -> RegressionTest:
    return RegressionTest(
        framework="pytest",
        file_path="tests/test_regression_fake.py",
        test_code="def test_placeholder():\n    assert True\n",
        test_name="test_placeholder",
        explanation="Fake provider placeholder test.",
        setup_requirements=[],
    )


def _fake_postmortem(_: LLMRequest) -> PostmortemProse:
    return PostmortemProse(
        summary="Fake provider placeholder summary.",
        root_cause_narrative="See root_cause_summary above; generated offline.",
        resolution_narrative="Fix applied and verified by the debug loop's check suite.",
        went_well="Detection and diagnosis were automated end to end.",
        went_wrong="No real model was used for this report (fake provider).",
        action_items=["Re-run with a real LLM provider for a production-quality report."],
    )


_FIXTURES: dict[type[BaseModel], Callable[[LLMRequest], BaseModel]] = {
    Classification: _fake_classification,
    Diagnosis: _fake_diagnosis,
    FixEvaluation: _fake_evaluation,
    RemediationDraft: _fake_remediation,
    RegressionTest: _fake_test,
    PostmortemProse: _fake_postmortem,
}


class FakeLLMProvider:
    name = "fake"

    def __init__(self, overrides: dict[type[BaseModel], Callable[[LLMRequest], BaseModel]] | None = None):
        self._fixtures = {**_FIXTURES, **(overrides or {})}

    async def generate(self, request: LLMRequest) -> LLMResult:
        start = time.perf_counter()
        factory = self._fixtures.get(request.output_schema)
        if factory is None:
            raise NotImplementedError(
                f"FakeLLMProvider has no fixture for {request.output_schema.__name__}; "
                "register one via overrides={...}"
            )
        parsed = factory(request)
        latency_ms = int((time.perf_counter() - start) * 1000)
        return LLMResult(
            parsed=parsed,
            stop_reason="end_turn",
            usage=Usage(input_tokens=0, output_tokens=0),
            cost_usd=0.0,
            latency_ms=latency_ms,
            model="fake-deterministic",
            provider=self.name,
            raw=None,
        )
